FROM amazonlinux:2

RUN yum update -y && \
    yum install -y \
    python3 \
    python3-pip \
    zip && \
    yum -y clean all

# Atualiza o pip para a versão mais recente
RUN python3 -m pip install --upgrade pip


