FROM python:3.8

# Instalando pacotes adicionais, se necessário
RUN apt-get update && \
    apt-get install -y \
    zip \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Atualizando o pip
RUN python3.8 -m pip install --upgrade pip


